### ISSUE TITLE
Adding Window support

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/fftw-feedstock#2]
Would be nice to get a Windows package supported here.

**Comment by jakirkham** [comment]
To get this to work, someone will need to do one of the following

1. Make a custom CMake file.
2. Build using MinGW-w64 toolchain
3. Repackage an existing copy of FFTW from MSYS2.

Right now, I think one of these last two looks like the most reasonable way to go. It is just a question of what we decide for conda-forge as a whole. So, this will be a topic for our next meeting.

**Comment by shadowwalkersb** [comment]
Any updates on this? Any way I can help with any of the three proposals above?

**Comment by jakirkham** [comment]
Honestly PRs welcome. Sorry, but I don't have time to further the cause myself.

**Comment by shadowwalkersb** [comment]
I am looking into MinGW, but also can try CMake way, too.

**Comment by shadowwalkersb** [comment]
Is MinGW supported as an installer? I am a bit confused seeing all the discussions on MSYS2. What is the recommended way of building for Windows?

**Comment by jakirkham** [comment]
Do you have any thoughts on this, @mingwandroid? Would it be worth considering reusing the FFTW package from MSYS2 or should we be building this from scratch? If the latter, would it be possible to use `make` to drive the process as was done with `icu` or would it be worthwhile to consider writing a CMake file to make this happen? Sorry if these are stupid questions. Just trying to muse over the possible options I have seen elsewhere and understand their applicability to other problems.

**Comment by jakirkham** [comment]
Also, it would be great to hear from @patricksnape and/or @ukoethe who have tried the CMake approach. Maybe we could investigate trying something similar here and get an idea of how challenging that might be to do.

**Comment by shadowwalkersb** [comment]
I have submitted a PR for a recipe that downloads pre-built binaries, #11 , but it is not working. conda doesn't seem to package all copied .lib and .dll files. Would be nice to get some feedback on the PR to see if that's something to pursue or complete waste of time.

**Comment by patricksnape** [comment]
As far as I can tell the fftw build is pretty complicated. However, there does appear to be some [Visual Studio Solution Files](ftp://ftp.fftw.org/pub/fftw/fftw-3.3-libs-visual-studio-2010.zip) which we may be able to use and use the `devenv.exe` to upgrade the solution file (`devenv.exe FreeImage.2008.sln /Upgrade`). I think that @ukoethe is probably the best [person to ask](https://github.com/ukoethe/ilastik-build/blob/master/fftw.cmake)?

**Comment by shadowwalkersb** [comment]
Out of the [Visual Studio Solutions](http://www.fftw.org/install/windows.html) available there only `fftw-3.2.2-vs2008.zip` is **VC9** which is needed by conda-forge, right? Unfortunately, the fftw source is **version 3.2**. When I tried to run the solution with **v3.3**, it couldn't find some of the source files. All the other **fftw-3.3** solutions are for higher Visual Studio versions. So, `devenv.exe FFFTW.2008.sln /Upgrade` won't do anything for us. Wish there was `devenv.exe FFFTW.2013.sln /Downgrade`. Solutions in [fftw-3.3-libs.sln](http://www.fftw.org/install/windows.html) seem to be **V11**.

**Comment by shadowwalkersb** [comment]
Maybe, it is possible to update VC9 sln with the `fftw-3.3` source? If so, where should the solution be hosted? Part of the recipe, maybe?

**Comment by jakirkham** [comment]
There is a [tool]( https://sourceforge.net/projects/vspc/ ) for updating really old solutions, which may be of some help.

**Comment by jakirkham** [comment]
Putting the solutions in the recipe is fine with me.

**Comment by jakirkham** [comment]
Agreed @patricksnape. Trying to get some clarification on the licensing of that recipe. See discussion in commit ( https://github.com/ilastik/ilastik-build-conda/commit/466f2b3df61df652a596b0972d800010a2aca80a ).

**Comment by ukoethe** [comment]
Sorry for the late response, I was offline for holidays.

Regarding the Windows build of FFTW 3.3: I ended up writing my own cmake scripts -- this turned out to be faster and safer than alternative workarounds, see https://github.com/ilastik/ilastik-build-conda/tree/toolset-config/fftw/cmake. (I might try to contribute this to the FFTW project, but currently have no time to prepare a PR.)

**Comment by shadowwalkersb** [comment]
There is already a PR, although broken. Please, see the [conversation](https://github.com/conda-forge/fftw-feedstock/pull/13#issuecomment-244286074). Would you mind if we borrowed your [CMakeLists](https://github.com/ilastik/ilastik-build-conda/blob/toolset-config/fftw/cmake/CMakeLists.txt) and go from there?

**Comment by ukoethe** [comment]
> Would you mind if we borrowed your CMakeLists and go from there?

Not at all, go ahead. Note that you also need [config.h](https://github.com/ilastik/ilastik-build-conda/blob/toolset-config/fftw/cmake/config.h) (I hard-wired it for my purposes. Ideally, it should be generated by cmake.)

**Comment by shadowwalkersb** [comment]
Thanks, I'll see what I can do.

**Comment by jakirkham** [comment]
Could you please [clarify]( https://github.com/ilastik/ilastik-build-conda/commit/466f2b3df61df652a596b0972d800010a2aca80a ) what is going on with the license of that file, @ukoethe? I'd really strongly prefer not to have GPL'd files making their way into conda-forge if it can be avoided. It seems like the license was only meant for `ilastik`, but it seems to be in the top level directory.

**Comment by ukoethe** [comment]
I'll happily put it onto the public domain, if you wish.

**Comment by jakirkham** [comment]
SGTM. Thanks @ukoethe.

**Comment by shadowwalkersb** [comment]
There is no easy way of automating generation of `config.h` using CMake on Windows. I played with a python script that replaces `#undef` s with `#cmakedefine`, then had cmake to check for some system headers and sizes of types. But, this is basically re-implementing `autotools` (I guess ?). The only practical solution to build from source on Windows, at least what I can see, is to have `config.h` edited manually or, just download pre-built binaries. Not sure if it's worth the effort to try to build from source.

**Comment by ukoethe** [comment]
I think `#cmakedefine` was specifically designed to make the transition from autotools easy. Most checks provided by autotools have a corresponding pre-defined check in cmake, so the transition is mostly a simple syntax translation. If you come up with a proper cmake-based build, hopefully the FFTW authors will accept a pull request -- this would be the cleanest solution.

OTOH, since FFTW is a C library, reusing official pre-built binaries might be good enough.

**Comment by shadowwalkersb** [comment]
Can we make use of `configure` on Windows somehow? Maybe, in cygwin environment or similar. This way most of the config.h will be populated. Especially, the system related macros. Then, we can use CMake to set things like ENABLE_*.

A PR upstream looks demanding. Even, `config.h.in` is automatically generated. Personally, I wouldn't want to write autotools scripts. Maybe, preparing a `config.h.in` can make things easier for them to adapt it to their autotools script. But, I am not willing to go down that road just yet.

**Comment by shadowwalkersb** [comment]
But then, if we use `configure`, why not go all the way through with `make` and `make install` afterwards, but switch to CMake in the middle? No point in doing that, I guess?

**Comment by shadowwalkersb** [comment]
Raised upstream ( https://github.com/FFTW/fftw3/issues/75 ).

**Comment by mingwandroid** [comment]
@shadowwalkersb: You can use `configure` on Windows using `conda-build` without resorting to installing `Cygwin` which would pick settings for a POSIX-like environment anyway, unless you were to also install mingw-w64 cross toolchains and then fix `fftw` to configure for cross compilation where necessary (it's likely ok though).

If you want a `config.h`, then you can generate one from a build of my [fftw-feedstock](https://github.com/mingwandroid/fftw-feedstock), however since `mingw-w64` and `MSVC` are not entirely compatible, the `config.h` may need a little tweaking. Here are the contents from a `conda-build` I just ran:

```
/* config.h.  Generated from config.h.in by configure.  */
/* config.h.in.  Generated from configure.ac by autoheader.  */

/* Define if CNTVCT is 64 bits readable on armv7a */
/* #undef ARMV7A_HAS_CNTCVT */

/* Define if CNTVCT_EL0 is 64 bits readable on armv8 */
/* #undef ARMV8_HAS_CNTCVT_EL0 */

/* Define to compile in long-double precision. */
/* #undef BENCHFFT_LDOUBLE */

/* Define to compile in quad precision. */
/* #undef BENCHFFT_QUAD */

/* Define to compile in single precision. */
#define BENCHFFT_SINGLE 1

/* Define to one of `_getb67', `GETB67', `getb67' for Cray-2 and Cray-YMP
   systems. This function is required for `alloca.c' support on those systems.
   */
/* #undef CRAY_STACKSEG_END */

/* Define to 1 if using `alloca.c'. */
/* #undef C_ALLOCA */

/* Define to disable Fortran wrappers. */
#define DISABLE_FORTRAN 1

/* Define to dummy `main' function (if any) required to link to the Fortran
   libraries. */
/* #undef F77_DUMMY_MAIN */

/* Define to a macro mangling the given C identifier (in lower and upper
   case), which must not contain underscores, for linking with Fortran. */
/* #undef F77_FUNC */

/* As F77_FUNC, but for C identifiers containing underscores. */
/* #undef F77_FUNC_ */

/* Define if F77_FUNC and F77_FUNC_ are equivalent. */
/* #undef F77_FUNC_EQUIV */

/* Define if F77 and FC dummy `main' functions are identical. */
/* #undef FC_DUMMY_MAIN_EQ_F77 */

/* C compiler name and flags */
#define FFTW_CC "gcc  -I/c/Users/builder/mc-x64-3.5/conda-bld/fftw-feedstock_1477495409885/_b_env/include"

/* Define to enable extra FFTW debugging code. */
/* #undef FFTW_DEBUG */

/* Define to enable alignment debugging hacks. */
/* #undef FFTW_DEBUG_ALIGNMENT */

/* Define to enable debugging malloc. */
/* #undef FFTW_DEBUG_MALLOC */

/* Define to enable the use of alloca(). */
#define FFTW_ENABLE_ALLOCA 1

/* Define to compile in long-double precision. */
/* #undef FFTW_LDOUBLE */

/* Define to compile in quad precision. */
/* #undef FFTW_QUAD */

/* Define to enable pseudorandom estimate planning for debugging. */
/* #undef FFTW_RANDOM_ESTIMATOR */

/* Define to compile in single precision. */
#define FFTW_SINGLE 1

/* Define to 1 if you have the `abort' function. */
#define HAVE_ABORT 1

/* Define to 1 if you have `alloca', as a function or macro. */
#define HAVE_ALLOCA 1

/* Define to 1 if you have <alloca.h> and it should be used (not on Ultrix).
   */
/* #undef HAVE_ALLOCA_H */

/* Define to enable Altivec optimizations. */
/* #undef HAVE_ALTIVEC */

/* Define to 1 if you have the <altivec.h> header file. */
/* #undef HAVE_ALTIVEC_H */

/* Define if you have enabled the cycle counter on ARMv8 */
/* #undef HAVE_ARMV8CC */

/* Define to enable AVX optimizations. */
#define HAVE_AVX 1

/* Define to enable AVX2 optimizations. */
/* #undef HAVE_AVX2 */

/* Define to enable AVX512 optimizations. */
/* #undef HAVE_AVX512 */

/* Define to enable 128-bit FMA AVX optimization */
/* #undef HAVE_AVX_128_FMA */

/* Define to 1 if you have the `BSDgettimeofday' function. */
/* #undef HAVE_BSDGETTIMEOFDAY */

/* Define to 1 if you have the `clock_gettime' function. */
#define HAVE_CLOCK_GETTIME 1

/* Define to 1 if you have the `cosl' function. */
#define HAVE_COSL 1

/* Define to 1 if you have the <c_asm.h> header file. */
/* #undef HAVE_C_ASM_H */

/* Define to 1 if you have the declaration of `cosl', and to 0 if you don't.
   */
#define HAVE_DECL_COSL 1

/* Define to 1 if you have the declaration of `cosq', and to 0 if you don't.
   */
#define HAVE_DECL_COSQ 0

/* Define to 1 if you have the declaration of `drand48', and to 0 if you
   don't. */
#define HAVE_DECL_DRAND48 0

/* Define to 1 if you have the declaration of `memalign', and to 0 if you
   don't. */
#define HAVE_DECL_MEMALIGN 0

/* Define to 1 if you have the declaration of `posix_memalign', and to 0 if
   you don't. */
#define HAVE_DECL_POSIX_MEMALIGN 0

/* Define to 1 if you have the declaration of `sinl', and to 0 if you don't.
   */
#define HAVE_DECL_SINL 1

/* Define to 1 if you have the declaration of `sinq', and to 0 if you don't.
   */
#define HAVE_DECL_SINQ 0

/* Define to 1 if you have the declaration of `srand48', and to 0 if you
   don't. */
#define HAVE_DECL_SRAND48 0

/* Define to 1 if you have the <dlfcn.h> header file. */
/* #undef HAVE_DLFCN_H */

/* Define to 1 if you don't have `vprintf' but do have `_doprnt.' */
/* #undef HAVE_DOPRNT */

/* Define to 1 if you have the `drand48' function. */
/* #undef HAVE_DRAND48 */

/* Define if you have a machine with fused multiply-add */
/* #undef HAVE_FMA */

/* Define to enable generic (gcc) 128-bit SIMD optimizations. */
/* #undef HAVE_GENERIC_SIMD128 */

/* Define to enable generic (gcc) 256-bit SIMD optimizations. */
/* #undef HAVE_GENERIC_SIMD256 */

/* Define to 1 if you have the `gethrtime' function. */
/* #undef HAVE_GETHRTIME */

/* Define to 1 if you have the `gettimeofday' function. */
#define HAVE_GETTIMEOFDAY 1

/* Define to 1 if hrtime_t is defined in <sys/time.h> */
/* #undef HAVE_HRTIME_T */

/* Define to 1 if you have the <intrinsics.h> header file. */
/* #undef HAVE_INTRINSICS_H */

/* Define to 1 if you have the <inttypes.h> header file. */
#define HAVE_INTTYPES_H 1

/* Define if the isnan() function/macro is available. */
#define HAVE_ISNAN 1

/* Define to enable KCVI optimizations. */
/* #undef HAVE_KCVI */

/* Define to 1 if you have the <libintl.h> header file. */
/* #undef HAVE_LIBINTL_H */

/* Define to 1 if you have the `m' library (-lm). */
#define HAVE_LIBM 1

/* Define to 1 if you have the `quadmath' library (-lquadmath). */
/* #undef HAVE_LIBQUADMATH */

/* Define to 1 if you have the <limits.h> header file. */
#define HAVE_LIMITS_H 1

/* Define to 1 if the compiler supports `long double' */
#define HAVE_LONG_DOUBLE 1

/* Define to 1 if you have the `mach_absolute_time' function. */
/* #undef HAVE_MACH_ABSOLUTE_TIME */

/* Define to 1 if you have the <mach/mach_time.h> header file. */
/* #undef HAVE_MACH_MACH_TIME_H */

/* Define to 1 if you have the <malloc.h> header file. */
#define HAVE_MALLOC_H 1

/* Define to 1 if you have the `memalign' function. */
/* #undef HAVE_MEMALIGN */

/* Define to 1 if you have the <memory.h> header file. */
#define HAVE_MEMORY_H 1

/* Define to 1 if you have the `memset' function. */
#define HAVE_MEMSET 1

/* Define to enable use of MIPS ZBus cycle-counter. */
/* #undef HAVE_MIPS_ZBUS_TIMER */

/* Define if you have the MPI library. */
/* #undef HAVE_MPI */

/* Define to enable ARM NEON optimizations. */
/* #undef HAVE_NEON */

/* Define if OpenMP is enabled */
/* #undef HAVE_OPENMP */

/* Define to 1 if you have the `posix_memalign' function. */
/* #undef HAVE_POSIX_MEMALIGN */

/* Define if you have POSIX threads libraries and header files. */
/* #undef HAVE_PTHREAD */

/* Define to 1 if you have the `read_real_time' function. */
/* #undef HAVE_READ_REAL_TIME */

/* Define to 1 if you have the `sinl' function. */
#define HAVE_SINL 1

/* Define to 1 if you have the `snprintf' function. */
#define HAVE_SNPRINTF 1

/* Define to 1 if you have the `sqrt' function. */
#define HAVE_SQRT 1

/* Define to enable SSE/SSE2 optimizations. */
#define HAVE_SSE2 1

/* Define to 1 if you have the <stddef.h> header file. */
#define HAVE_STDDEF_H 1

/* Define to 1 if you have the <stdint.h> header file. */
#define HAVE_STDINT_H 1

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Define to 1 if you have the <strings.h> header file. */
#define HAVE_STRINGS_H 1

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define to 1 if you have the `sysctl' function. */
/* #undef HAVE_SYSCTL */

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/sysctl.h> header file. */
/* #undef HAVE_SYS_SYSCTL_H */

/* Define to 1 if you have the <sys/time.h> header file. */
#define HAVE_SYS_TIME_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* Define to 1 if you have the `tanl' function. */
/* #undef HAVE_TANL */

/* Define if we have a threads library. */
#define HAVE_THREADS 1

/* Define to 1 if you have the `time_base_to_time' function. */
/* #undef HAVE_TIME_BASE_TO_TIME */

/* Define to 1 if the system has the type `uintptr_t'. */
#define HAVE_UINTPTR_T 1

/* Define to 1 if you have the <unistd.h> header file. */
#define HAVE_UNISTD_H 1

/* Define to 1 if you have the `vprintf' function. */
#define HAVE_VPRINTF 1

/* Define to enable IBM VSX optimizations. */
/* #undef HAVE_VSX */

/* Define to 1 if you have the `_mm_free' function. */
/* #undef HAVE__MM_FREE */

/* Define to 1 if you have the `_mm_malloc' function. */
/* #undef HAVE__MM_MALLOC */

/* Define if you have the UNICOS _rtc() intrinsic. */
/* #undef HAVE__RTC */

/* Define to the sub-directory in which libtool stores uninstalled libraries.
   */
#define LT_OBJDIR ".libs/"

/* Name of package */
#define PACKAGE "fftw"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT "fftw@fftw.org"

/* Define to the full name of this package. */
#define PACKAGE_NAME "fftw"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "fftw 3.3.5"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "fftw"

/* Define to the home page for this package. */
#define PACKAGE_URL ""

/* Define to the version of this package. */
#define PACKAGE_VERSION "3.3.5"

/* Define to necessary symbol if this constant uses a non-standard name on
   your system. */
/* #undef PTHREAD_CREATE_JOINABLE */

/* The size of `double', as computed by sizeof. */
#define SIZEOF_DOUBLE 8

/* The size of `fftw_r2r_kind', as computed by sizeof. */
#define SIZEOF_FFTW_R2R_KIND 4

/* The size of `float', as computed by sizeof. */
#define SIZEOF_FLOAT 4

/* The size of `int', as computed by sizeof. */
#define SIZEOF_INT 4

/* The size of `long', as computed by sizeof. */
#define SIZEOF_LONG 4

/* The size of `long long', as computed by sizeof. */
#define SIZEOF_LONG_LONG 8

/* The size of `MPI_Fint', as computed by sizeof. */
/* #undef SIZEOF_MPI_FINT */

/* The size of `ptrdiff_t', as computed by sizeof. */
#define SIZEOF_PTRDIFF_T 8

/* The size of `size_t', as computed by sizeof. */
#define SIZEOF_SIZE_T 8

/* The size of `unsigned int', as computed by sizeof. */
#define SIZEOF_UNSIGNED_INT 4

/* The size of `unsigned long', as computed by sizeof. */
#define SIZEOF_UNSIGNED_LONG 4

/* The size of `unsigned long long', as computed by sizeof. */
#define SIZEOF_UNSIGNED_LONG_LONG 8

/* The size of `void *', as computed by sizeof. */
/* #undef SIZEOF_VOID_P */

/* If using the C implementation of alloca, define if you know the
   direction of stack growth for your system; otherwise it will be
   automatically deduced at runtime.
	STACK_DIRECTION > 0 => grows toward higher addresses
	STACK_DIRECTION < 0 => grows toward lower addresses
	STACK_DIRECTION = 0 => direction of growth unknown */
/* #undef STACK_DIRECTION */

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* Define to 1 if you can safely include both <sys/time.h> and <time.h>. */
#define TIME_WITH_SYS_TIME 1

/* Define if we have and are using POSIX threads. */
/* #undef USING_POSIX_THREADS */

/* Version number of package */
#define VERSION "3.3.5"

/* Use common Windows Fortran mangling styles for the Fortran interfaces. */
/* #undef WINDOWS_F77_MANGLING */

/* Include g77-compatible wrappers in addition to any other Fortran wrappers.
   */
/* #undef WITH_G77_WRAPPERS */

/* Use our own aligned malloc routine; mainly helpful for Windows systems
   lacking aligned allocation system-library routines. */
#define WITH_OUR_MALLOC 1

/* Use low-precision timers, making planner very slow */
/* #undef WITH_SLOW_TIMER */

/* Define to empty if `const' does not conform to ANSI C. */
/* #undef const */

/* Define to `__inline__' or `__inline' if that's what the C compiler
   calls it, or to nothing if 'inline' is not supported under any name.  */
#ifndef __cplusplus
/* #undef inline */
#endif

/* Define to `unsigned int' if <sys/types.h> does not define. */
/* #undef size_t */
```

You'd need one for 32-bit and one for 64-bit, the above is 64-bit, besides that, the `fftw-feedstock` runs `configure` 3 times for different configurations so you might need 6 `config.h` files.

You might be able to take my feedstock and let it run `configure`, then instead of running `make` run `cmake` then `cmake --build` to do the build, but I have no idea how well `MSVC` would handle `fftw` sources, I guess it handles them to some extent given https://github.com/conda-forge/fftw-feedstock/issues/2#issuecomment-245012963.

But as @ukoethe pointed out, `cmake` has support for running compilation and link tests to generate `config.h` files *anyway* so using both `configure` and `cmake` seems a bit pointless. I would just work adding that support to the `CMakeLists.txt` file(s).

Alternatively you could use the DLLs built by my `fftw-feedstock` and see if they work for you in practice. You would need to generate `MSVC` compatible import libraries using `m2w64-toolchain`'s `gendef` and Visual Studios `lib` as-per: https://github.com/mingwandroid/conda-recipes/blob/master/rstudio/bld.bat#L35-L36.

**Comment by shadowwalkersb** [comment]
Thanks for the detailed write-up, @mingwandroid . I've been using the pre-built dlls on my project. PR ( https://github.com/conda-forge/fftw-feedstock/pull/11 ) does exactly (?) what you do on your fftw-feedstock. But the effort here is to build from source on conda-forge, if possible. I am starting to question if it's worth jumping through all these hoops, though. 😩

**Comment by mingwandroid** [comment]
PR #11 does nothing at all like what mine does. I build from source.

**Comment by mingwandroid** [comment]
@jakirkham How do I enable AppVeyor for my feedstock?

**Comment by shadowwalkersb** [comment]
> PR #11 does nothing at all like what mine does. I build from source.

@mingwandroid Sorry, my mistake. As I said, 😫 .

**Comment by jschueller** [comment]
@mingwandroid enable win in your meta.yaml then rerender

**Comment by shadowwalkersb** [comment]
Got a response from upstream (FFTW/fftw3#75) and posted what I had in mind. Please, chime in to make sure we get this right.

**Comment by hadim** [comment]
With #11 we have a quick and easy way to get the ffwt package for Windows while with #17 we seem not so far to get a Windows build compiled on AppVeyor.

Could we just use #11 at the moment and then try to get #17 done ? 

I don't see why not.

**Comment by bmorris3** [comment]
I second @hadim – a windows build would be very useful.

**Comment by jakirkham** [comment]
It would be great for sure. However, there are 2 or 3 different proposals circulating in various states. It would be nice if someone with time and interest wrote up an unbiased comparison of their merits.

**Comment by shadowwalkersb** [comment]
fftw folks seem to be thrilled(!) about the cmake-based builds. See https://github.com/FFTW/fftw3/pull/80#issuecomment-272743478. If anyone wants to weigh in the conversation, please chime in.

**Comment by shadowwalkersb** [comment]
> It would be great for sure. However, there are 2 or 3 different proposals circulating in various states. It would be nice if someone with time and interest wrote up an unbiased comparison of the proposals and their merits.

This may not be an ideal write up, nor unbiased, but FWICT the proposals are:

1. Use pre-built binaries, #11 .
2. Use mingw, #17 .
3. Build from source.

Number 2 is broken and needs to be fixed, number 3 can't move forward without cmake support or something very hacky and doesn't seem to be happening any time soon. Number 1 may not be ideal, but at least works.

**Comment by danielkaneider** [comment]
Whats the status of this? Current 3.3.6 release doesn't seem to be supported on windows any more. There are neither precompiled dlls, nor any working VC project file. CMake would be a good way to go, since it brings windows and unix distribution on the same level.

@shadowwalkersb CMake supports some kind of `configure` using `configure_file`

**Comment by rmcgibbo** [comment]
It seems like https://github.com/Microsoft/vcpkg/tree/master/ports/fftw3 could be of some utility.

**Comment by grlee77** [comment]
Thanks @rmcgibbo.  I was not aware of that Microsoft repository.  It looks like the `vcpkg` repository is MIT licensed too, so no problems there. 

I think it is worth trying this approach in a PR and seeing how it goes.  I can try that unless you were already planning to work on it?

**Comment by grlee77** [comment]
I made an initial test of the feasibility of the CMAKE approach in #25.  I cancelled the non-Windows CI and ran only a single case on Appveyor.  The build completes, but there are still a few issues to resolve.  Do others think it is worth pursuing this approach further?

**Comment by mingwandroid** [comment]
The msys2 channel has an fftw package now. It works for all visual studio runtimes. I'll make sure it's on defaults soon.

**Comment by ras0219-msft** [comment]
@grlee77 If you go this route, we'd be happy to take changes back upstream into Vcpkg to try to keep these two (the conda feedstock and the vcpkg port) somewhat synchronized. Hopefully that way we can share the maintenance burden of the CMake script whenever FFTW updates.

**Comment by mingwandroid** [comment]
`conda install m2w64-fftw` if you want what we'll use on defaults (I don't believe that any CMake based-build will work on Python 2.7 since `fftw` uses C99) so in this case compiling with mingw-w64 is the best choice.

**Comment by grlee77** [comment]
I had seen the WIP/PR for an msys2 build here, but wasn't aware of the completed package in the `msys2` channel.  Is there an advantage to continue to pursue a MSVC/CMake build as opposed to an msys2 one?

One other inconsistency between the MSVC/CMake build and the existing `conda-forge` packages is the use of OpenMP rather than POSIX threads, resulting in different library names (`fftw_omp.dll`, etc).

**Comment by grlee77** [comment]
> I don't believe that any CMake based-build will work on Python 2.7 since fftw uses C99

According to the build logs [here](https://ci.appveyor.com/project/conda-forge/fftw-feedstock/build/1.0.21), including the `msinttypes` package seems to have allowed the build to complete even for Python 2.7.  I haven't looked at the internals, but I guess this means that FFTW must not be using C99 complex floats as I don't think that is properly supported even in current MSVC.

The failures in #25 are currently due to invalid syntax in the `meta.yaml` at the testing stage.

**Comment by jakirkham** [comment]
It looks like FFTW is going to go the CMake direction as well. Please see PR ( https://github.com/FFTW/fftw3/pull/80 ).

**Comment by jakirkham** [comment]
Done with PR ( https://github.com/conda-forge/fftw-feedstock/pull/32 ).

**Comment by jakirkham** [comment]
Upstream has been recently accepted PR ( https://github.com/FFTW/fftw3/pull/103 ), which adds an option to build with CMake. This allows for Windows support. Though they are sorting out some issues with the Windows build. Would be good if any Windows experts here could help them out. Expect that we will be using whatever Windows solution upstream settles on in the near future.
