### ISSUE TITLE
meta.yaml tests

### ISSUE THREAD

**Issue by egpbos** [conda-forge/fftw-feedstock#41]
Just wondering: why are the tests in meta.yaml set to exit immediately on success? https://github.com/conda-forge/fftw-feedstock/blob/master/recipe/meta.yaml#L30 This way, only the first test is run, i.e. only the check for the existence of lib/libfftw3f.a is performed, while a whole array of additional tests are setup below that.

**Comment by beckermr** [comment]
I just fixed this. Appears to have been a bug.
