### ISSUE TITLE
Travis CI log length limit

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/fftw-feedstock#44]
We appear to be going over the [Travis CI log length limit]( https://travis-ci.org/conda-forge/fftw-feedstock/builds/348359641 ). While it says it will terminate our jobs, it seems to let them run anyways, which is fortunate. That said, we can't expect this to hold up forever. Would be good to fix our build to stay within this log length limit if possible or switch to CircleCI, whichever is easiest.

**Comment by beckermr** [comment]
Closing since we are on azure now.
