### ISSUE TITLE
Split off static builds

### ISSUE THREAD

**Issue by hmaarrfk** [conda-forge/fftw-feedstock#76]
It seems that in 
https://github.com/conda-forge/fftw-feedstock/pull/50
A discussion started on whether or not we should include the static files.

I believe conda-forge has since pushed away from static libraries.

Would it be acceptable to remove the static libraries from this package and deal with the issues when they arise downstream?
Can we split the package instead into two?
```
fftw-static   # not recommended but for downstream projects to migrate
fftw  # only dynamic modules
```

Thoughts?

**Comment by egpbos** [comment]
Sounds good to me.

**Comment by egpbos** [comment]
Maybe @beckermr has some thoughts, seeing as he was involved in that earlier discussion as well.
