### ISSUE TITLE
libgfortran issue downstream

### ISSUE THREAD

**Issue by ax3l** [conda-forge/fftw-feedstock#80]
Since the `mamba` upgrade in October, I see the following concretization issue in my downstream project:
```
The reported errors are:
- Encountered problems while solving:
-   - package fftw-3.3.10-nompi_h427eb53_101 requires libgfortran5 >=9.4.0, but none of the providers can be installed
```

My project is a plain C/C++ project:
https://github.com/conda-forge/warpx-feedstock/pull/33
and and declares the FFTW dependency here:
https://github.com/conda-forge/warpx-feedstock/blob/fe5437ec5282ebdbf4e43af96b8a894e26debb31/recipe/meta.yaml#L43

Should we try to rerender the feedstock and see if this solves it?

**Comment by jakirkham** [comment]
Sounds reasonable. Do you want to try?

**Comment by ax3l** [comment]
Thanks! Yes, PR in #81 :)
